### PR TITLE
Object access dot operator

### LINKED ISSUE #28: Dot operator and Identifiers for Object properties.
# Goal
Improve consistency, make Walt object types appear more like structs(which they are).

# Overview

Original issue (#22)

As of writing, object property access is performed via array subscript operator and string subscripts like so `obj['foo']`. This is not the ideal long-term solution and causes some confusion about the semantics of objects in Walt. 

The long-term solution is to provide a new dot `.` binary operator which would be a single way to access properties on an object type.

# Acceptance Criteria

- [ ]  The dot . operator which is not currently supported. We would need the tokenizer to recognize it (easy) and for the parser to convert it down to a plain old array subscript.
- [ ]  Unit tests
- [ ]  Removing/converting string property lookups, in examples and tests.
- [x] Identifiers as object definitions should work

### PR DESCRIPTION
**Pull request by Baransu**
Second attempt to resolve #28. New PR because I've started work from scratch and I want to keep clean git history.

This solution leverages parser rather than tokenizer so no new tokens were added to syntax. One not so nice part is checking if last operator and last operand in the `parser/expressions` are like we would like them. This probably can be improved but I'm counting on some feedback first.
I've also added error when we're trying to access object field that doesn't exist. New error inside Context: `TypeError` was introduced because it was more suitable for this type of error.

There are some formatting changes and they are not related to my PR but I was forced by prettier to add them because of wrong formatting on some files that were on `master` branch.

### CODE REVIEW

**Comment by Baransu** [comment]
Linting is failing because of the eslint rules conflicting with prettier output. Maybe it's a good idea to disable code formatting rules at all because we're forcing prettier formatting so after all there is no need to check them by eslint.

**Comment by ballercat** [comment]
The eslint + prettier setup is there to ensure properly formatted code is committed to master. Looking at the eslint errors they are legit. Strings must use double quotes, this is default prettier setup. The project uses mostly default prettier style + trailing commas.

**Comment by iddan** [comment]
Wasn't it agreed that no string access and declaration would be allowed to avoid confusion?

**Comment by Baransu** [comment]
But prettier soubleQuote is not always double quote but prefer double quote. https://prettier.io/docs/en/options.html#quotes

Using prettier in validation step ensures us that code formatting is correct so having eslint for that is unneccessary. In situations like this there is no way to have eslint and prettier pass because code is properly formated after prettier pass.

**Comment by ballercat** [comment]
I see what you mean now. Yeah, our eslint-rule for quotes is misconfigured https://eslint.org/docs/rules/quotes#avoidescape we should have had an `avoidEscape` option enabled. 

My primary concern was that it would be difficult to track down what is wrong with the source if there is only prettier validation as it'll simply point a file should be prettified but not which line/why it's failing. We could discuss disabling formatting rules, even though wouldn't really buy us anything.

For the errors you're getting, just edit the quote rule as it's misconfigured.

**Comment by Baransu** [comment]
Waiting for review and initial feedback so I can improve things and convert examples/documentation.

**Comment by ballercat** [comment]
My initial feedback is similar to the original PR.

Since the `.` dot operator is already a binary operator handled by the parser. Generating a node with two params for us for pretty much free:

```js
[
  targetNode,
  parameterNode
]
```

All we should need to do is to map the params to something array subscript can consume. Which is a `identifierNode.stringLiternalNode`. Check this part of the operator parser logic https://github.com/ballercat/walt/blob/296f1cb1d19188c29e63ea96b6873df94781ba20/src/parser/operator.js#L26

I don't really see a reason for us to keep track of the tokens in expression to figure out if it's an access operator or not.

**Comment by ballercat** [comment]
I gave updating this branch a shot, but it's way out of date by this point. It's been a while since any updates, so I think I'm going to consider this PR abandoned and implement the dot operator a bit differently. At this points it's a bit of a blocker for some other features.

**Comment by ballercat** [comment]
Fantastic. I was able to necromance the branch! 

I hope you see why I went in a different direction. The changes to AST generators and validation made this feature a 3 line change.

Thanks for the help!

**Pull request merged**
