### PR TITLE
Travis eslint validation, flowtype rules

### PR DESCRIPTION
**Pull request by ballercat**
#29 

* Add eslint validation script
* Flowtype rules
* ran `eslint --fix`

### CODE REVIEW

**Comment by ForsakenHarmony** [comment]
do you not want dangling commas? they're good for git diffs

**Comment by ballercat** [comment]
They do make diffs slightly better when adding to an existing list, but I don't think that scenario is significant enough to optimize.

I don't use them, and I already wrote so much code that I'm airing on the side of consistency.

**Comment by ForsakenHarmony** [comment]
pretty sure eslint can fix it

**Comment by ballercat** [comment]
I would be open to them I guess. I  don't feel that strongly about using them or not, and it's just not part of my current workflow. I can see that there might be a marginal benefit for not a lot of effort, so if you want to `--fix` them and submit the changes then that's fine 👍

**Pull request merged**
