### PR TITLE
tests: add Node.js 10

### PR DESCRIPTION
**Pull request by DanielRuf**

### CODE REVIEW

**Comment by DanielRuf** [comment]
And finally we found a fialing build thanks to the addition of Node.js 10.

https://travis-ci.com/ballercat/walt/jobs/151169482

`node-sass` has to be upgraded.

**Comment by DanielRuf** [comment]
Seems we caught another issue. Can someone take a closer look?

https://travis-ci.com/ballercat/walt/jobs/151205830

**Comment by ballercat** [comment]
Thanks for this.

I'm taking a look at the test failure now.

**Comment by ballercat** [comment]
Also, shouldn't node 10 be LTS already? If it's close I'd rather just test against it and not both 8 & 10. I'd like to keep these test pipelines quick.

**Comment by DanielRuf** [comment]
10 should become LTS this month, see https://github.com/nodejs/Release/blob/master/README.md

**Comment by DanielRuf** [comment]
But there are always 2 LTS releases / branches and 8 EOL will take a while.

**Pull request merged**
